import { Fragment } from "react";
import Head from "next/head";
import Hero from "@/Components/HomePages/Hero";
import FeaturedPosts from "@/Components/HomePages/Featured-Posts";

const DUMMAY_DATA = [
  {
    slug: "ReactJs-is-a-framework-of-javascript",
    title: "ReactJs is a framework of javascript",
    image: "getting-started-nextjs.png",
    excerpt: "ReactJs is easy to learn & World most populer lenguage.",
    date: "10-09-2023",
  },
  {
    slug: "Getting-Started-with-NextJS",
    title: "Getting Started with NextJS",
    image: "getting-started-nextjs.png",
    excerpt: "NeatJS is a the React framework for production-it makes building fullstack React apps and sites a breaze and ships with bullt-in SSR.",
    date: "11-18-2023",
  },
  {
    slug: "Getting-Started-with-NextJS2",
    title: "Getting Started with NextJS",
    image: "getting-started-nextjs.png",
    excerpt: "NeatJS is a the React framework for production-it makes building fullstack React apps and sites a breaze and ships with bullt-in SSR.",
    date: "11-18-2023",
  },
  {
    slug: "Getting-Started-with-NextJS3",
    title: "Getting Started with NextJS",
    image: "getting-started-nextjs.png",
    excerpt: "NeatJS is a the React framework for production-it makes building fullstack React apps and sites a breaze and ships with bullt-in SSR.",
    date: "11-18-2023",
  },
];

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <FeaturedPosts posts={DUMMAY_DATA} />
    </Fragment>
  );
}
